language: java
sudo: required
addons:
  ulimit:
    nofile: 1048576
services:
- docker
jdk:
- oraclejdk8
script: "./gradlew clean test jar"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TPMHv3LUWpuX9Njo1A7zsrNk6Z0FDRv2xOG6lmxboiEg1nNX/ctfJfGpHpMbTnc1Q23ycVMj8DBoTG/gy7+2Qd9m6WY7JN0MmvYdhATKFWvRhnkJD0Jkt+yAkWYJfAIv7MOh0JFstC/9HZGgfvkIDaZPk3PhXN+6KpJVWPTqf6+g8lgtncrqM2GS03dArwzhnxdj0rQ+jQ0xjONcBpVPKBwcljTo3p3A6JtAlvtrXsVyswi9HZHZ9USS4CDYlwljDHjc/wtjrGK+td9kR45kxt0aBUWAdUKx0ueH1GB/h2H3AS8chy9fUttqSynY6fY+/a1gwt3TBtw6KeY5adn89YzxybH3Nj006ilb8wyARBHS6fsAvaKLBFrdoh9ayq8GAb/bvw+b+pO/L6aq/ZSLzeZrVKgpL6C+Zh2/0cZdWt/AaT9vszwShxqcbjmJdzuvAyLyaGx1ELFZTwf4HPE8JokQCaZY4SPe2HOOteh9yb3FDAwahuQVqHWTB5p1k0zUBz1GdokjMrJ28XJErKQvaI4HRmcwso8nU1bvVntkj4jB8OkJE+EL6MeqznNLnJD+akwj0q0QgSvTjpjeobgoCLic5MbcL32+D25PE+PaOM13IJMkCJBAPfUTgyU2ZV6x4Gy3SsOEndpvi9fRtsuj3AGCjpibp3wFHFt/XPChGX0=
  file: "./build/libs/mongoose-storage-driver-fs.jar"
  on:
    tags: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: Awm5ZsL8OJZTu6laZWGgm0kixqCQaAWnR7du+tMphQEra62axza+M5Dtj6OqmLXygtjirKUawEODN9oW64YAUqvWBy3ZV6b+x43Ixbh3dTTTGCkk9o0AbguGN3mcVyASf/FhXHsCR209dEmBN7rOxv1H/FXOsTBL7FrkrjB25SwRouiJa5q3ji2HsZXEIV8kpZ+l8eb8X4zuMpWfUJtqtzZ5Ozbr2UrL3EadImhfFzDqNggDZBZIYL5bsZk/7dJ2ATpHznqaWfRWw7KxKjZ/QCdjoquVQEnWt6Mg2dUh3eDzoynnDor7TTUrekSsJLFecfyRL6+1Y3KrgPxj1eiRqllCKbVNLzQltU5lrM5vMA3SzAJ/5HoRbqRiksKJrw+e/sE0WKeh48O+qMkdmOpLtdrdZMq9cguSmFUFTwOfh3X02z7KcdGixYNcu2jrwuPxt02hc0NxF2viv5vriagtFredTcGIT8hDUNh4ARCFsm2JH5TXkgdovTUYNfd1EFMVKsPp7WC73cRv+Hreex1MmkEbQkP9iHRwxVf7du3gWhJOvtiaXrZIk1Hi9lEiMjuqTrBFh5wpsOWM6Zhj1JCrdgH9OqmeatOrstZbjJu3U/ZEIsCsxFvI37+wpa2cgtGVUVgMxFQm2XEPzUM3QdU/1rsDVXIW6oylTlCM85qPy2Q=
  - secure: rqGxUKnBladWD+2SuRBit/eLnJD/nZNoT0Gl1HW0GiQaI+OL38PDtIrEiQJBI8yBjj70SGGIMCaGhXifpQLUIBcnBLjtFj4ztvhIG9ooDQZcf6jVu0BgpfNzXgHKKJN4uM1bQb2upljmVaIrSDfrYitVHtPoxgp0JWESym/a2ITwhZ863OgmqKsVJm3uFhHJC1qle6OUTcgT0fI+o/XVATuqu6WbxH6YdUgIEwCjiaA8xcCY0TXt89R2cu7Tq9GbdNQVzTxwWpBRP7/JC9pzwQTsCNsAA++rkvMkNb2StPK5xDmqDNf91hfjv0ZNIxhIRRBKRr8V7p9sb4dPOxjdZkcKFzGWaNxFMqa3cMts1BYki/ZeRDEJmmRk/Z2ocKfHh0C0MLfL9JGkeG355oEFclKDZbpLzMUlg/B+oxzht6NnXCmOw0LzJxcxq9m9zEbWCaXmPCRvdkGOG0Bj+MvEFgxfyXRPhOSJayggIXx02YZN1HfUiKUZg8p1M54HyOEpaQEzSfjMRaGXhCOW6kHbYpJFeJYI+4weEDaivTfts1RvnB/84ZGl4hY5faTUnV56KzKOreh8V6UfQiriMr5h5qdBnK1J7Olz0Bc+T2q33zL5rqgeMiEMq2+YDqsBfC/UwE/lO5S6PHyONKm16+lqrZY3ay/cvXrhb/Rll2gPxgk=
  - secure: JT3awhA8DPSKDmBv0ByCX1ri23rPDl5gKQr0XlR683L3pxjafyto3hHop0UDkztweQuFrXka+NnI3VJhEnfmccoK91v7C17SlfamqHGvp562AIXOBrSVKUgDdq8nDtPMvIcVj1SW/hyKlkLrTmPJYBjwpGN6moS67kN09S6p9RIDG3FqNSzmHmzqyGfFM41mY3gAXQLibjE5RLYiA+E4MMxww+O2ngln1eVRs0p025xPqFlW4n3z3DevhEmAv4jJ72lyNnDfb4SCm1Y41EIMrGE9wdspcSI3VNuB3lFpKobr5ynPH6kYZLgefJS5wcvqu1SgM6i45OyXCIOvpq94nf/PssvrSwk3aGNGTZLhdQ8brhSzbLS1tKJ2Ts4nCUAiq+OQx/jyOG7+xJTSQpZWG9QH8dHsNZnHmGFo48nrZifvMzjAln1jAhPdu97A2aV2atvUoPR+8HogvrDpdRjKRCkjicimQk0a2y4Ij30KwUfPD4ubpRTteTYUW2C4RVznCWzZrhPFQ2XYDxpPHgwG71UUwzGvEW83DEFSKOI7ohaBj2pksnJ429QHlGlb8HiQrbEP3tfutIVXY6teGYpZnZ2dDlgREzxdDHuzU8m/w19YUQUiyUrHdLEc5vSUOBclG59afeIHSgdXKtHLffv+7dvT1SZlYcmukTMeuvwLnKk=
  DOCKER_USER:
    secure: r4Jv836Vk20Ivs4F4R+rZ9IJf8byh3zaCyrmZK+I+u+cNXLLzS0+Yd7v48a1yNaksYhiRtCGG8vqWzS2O14tcIgMveCdIB8v5y5nSOCp9n0jDAmtUikf2tjYL58wPNy1vFdfiCVLLfjI91EdMIwA0B6SJES7FzZbeyfOn8+JJjX+/3KHVR9mgASaVvu23FbTbCqJyUQP18/PIPgPkSuzVwae+1CtyVDh7BtlKYjTwtMPly1Kcs3RLUVbDhO99ps0zdItgI2S/XDJO3wRwvCiR9EfNzaLWT3MPaiPQAQ6dR8wlwiwrPoAM0Ik1jLGMuQBas1TLXn9NcHj4NBq/m4gCGA77M0P1klT2MTxpMdtbJs2+KNW0KwHbUIxstCTM/Pc3TsaHL7W8ln2VqKabQdvgxf89GJWaKE004L0nfo7l9hgPqnQtoXSuyLpa5y6ztg0g37CsK08wMGcrWQ49OW2Gegeros6Nu/k5YFOCAwQ6kKg664wsaptS9dZuL3uI2NS9BVPTBq3wK5ynWzdTF9eiQI8FCaqWW0VsEBbr4eYFsH95VAJTNGI/AsUqBZ9zuxFQ9oJTRDfkq/PjmkHimZJfg/xXM/MalFsUiAZBISLTMKQAG7VbTo273tdh5pmCEYqzhbFSFsYw98s5T/NZksRh63D5hJCcVIqOkZ2kkydWNE=
  DOCKER_PASS:
    secure: OqsGKj/wOVpi3DWh4R4mMDNDNzn2lh9mmr/iDJobRIPHqE6a/t1IylfeO/GOYaIuQWxbLNtqhNGUOcLfn9reIWqFzYVeaCqWahIdLuMMTtX8+NjJHtzvu7tvO/DTs8VNPJh3UJryMXYqfOOgmL0tcmR1OqnIT3DxsmCXizWJBKzZVgnbNlRJU71YZRmMeyKxp3DSKLLWdS6mLHl/tHAOaOfK6KafAwWkMy0mWea8TY5rBTXc3ab/aRmRhHrXEi7WTIVnZ9NvarkJtsPzgQ5O8AgTN0QiJSTZJnfsAV/ejlNtmU3VLCsYr1K2OP+jY1+mtTL7BYxQbGcXQDd6Oie0dO9GJNgTwwfuE/NotFt08wvJ7MJTOJiapuyh/FUDmg6XxTRssqtvGGr54e4eI1DRelmlsRA76jCypVcX6yccQNM83CbAZjkgNE5wfe2pzo54J9CWGaY3ZvTnPWixPbqdgR+Ej5SSZQ9nB85Klk2UpNnyz4C+mSXbU9OjY/PJyFL4+jnIN06jRmY8TLsWYy3tpvQO1Bi7Hv17en5PHclykhayyiC4ztVMoG2ePdB4qhgT43eYSppg7/Smyry/jxmLiRNYGUlHvcpFqMsHrLMDWJ9h/fhJ9Kqfj8W0hBY3aVlwxcjOb54ZL5s24sF8v4mQwPkcPHqGGzgBwvbOLTU01+M=
before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
matrix:
  fast_finish: true
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=emcmongoose/mongoose-storage-driver-fs
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build --build-arg MONGOOSE_VERSION=next -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- export REPO=emcmongoose/mongoose-storage-driver-fs-service
- export DRIVER_VERSION=$TAG
- docker build --build-arg DRIVER_VERSION=$TAG -f docker/Dockerfile.storage-driver-service -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
