image:
  - Visual Studio 2017

environment:
  JAVA_HOME: "C:\\Progra~1\\Java\\jdk11"
  MAVEN_HOME: " C:\\Users\\appveyor\\.m2\\repository\\com\\github\\emc-mongoose"
#  HOME_DIR: C:\projects\mongoose-storage-driver-fs
  HOME_DIR: C:\.mongoose\ext\
  PATH_TO_TEST_LOGS: "C:\\projects\\mongoose-storage-driver-fs\\\build\\robotest"
  PYTHON: "C:\\Python37-x64"
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64

before_build:
  - cmd: cd %DRIVER_DIR%
  - cmd: mvn -v
  - ps: >
      $env:MONGOOSE_VERSION=$(type base\src\main\resources\config\defaults.yaml
      |  where { $_ -match "version"} | Select-String -Pattern '\b\d\.\d\.\d\b' -AllMatches
      | % { $_.Matches } | % { $_.Value })
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-storage-driver-nio:LATEST
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-storage-driver-coop:LATEST
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-base:LATEST
  - cmd: cd %MAVEN_HOME%
  - cmd: ECHO %MAVEN_HOME%
  - cmd: COPY %MAVEN_HOME%\mongoose-storage-driver-nio\4.2.1\mongoose-storage-driver-nio-4.2.1.jar  %HOME_DIR%
  - cmd: COPY %MAVEN_HOME%\mongoose-storage-driver-coop\4.2.1\mongoose-storage-driver-coop-4.2.1.jar %HOME_DIR%
  - cmd: COPY %MAVEN_HOME%\mongoose-base\4.2.1\mongoose-base-4.2.1.jar %HOME_DIR%

build: off
build_script:
  - cmd: cd %DRIVER_DIR%
  - cmd: gradlew.bat clean jar
  - cmd: git

before_test:
  - ps: >
        $env:MONGOOSE_VERSION=$(type base\src\main\resources\config\defaults.yaml
        |  where { $_ -match "version"} | Select-String -Pattern '\b\d\.\d\.\d\b' -AllMatches
        | % { $_.Matches } | % { $_.Value })
  - cmd: set PYTHONPATH=%HOME_DIR%\base\src\test\robot\lib;C:\Python37-x64\lib\site-packages
  - cmd: set PATH=%PATH%;C:\Python37-x64;C:\Python37-x64\Scripts
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "%PYTHON%\\python.exe -m pip install -U virtualenv"
  - cmd: "%PYTHON%\\python.exe -m pip install -U requests"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework-requests"
  - cmd: mkdir %PATH_TO_TEST_LOGS%
  # TODO also get mongoose base jar, coop driver, nio driver and put them to the proper place

test_script:
  - cmd: robot --outputdir %PATH_TO_TEST_LOGS% --suite api.storage --include "fs" base\src\test\robot

on_failure:
  - cmd: appveyor PushArtifact %PATH_TO_TEST_LOGS%\log.html
