image:
  - Visual Studio 2017

environment:
  JAVA_HOME: "C:\\Progra~1\\Java\\jdk11"
  MAVEN_HOME: "C:\\Users\\appveyor\\.m2\\repository\\com\\github\\emc-mongoose"
  HOME_DIR: "C:\\Users\\appveyor\\"
  DRIVER_DIR: "C:\\projects\\mongoose-storage-driver-fs\\"
  PATH_TO_TEST_LOGS: "C:\\projects\\mongoose-storage-driver-fs\\build\\robotest"
  PYTHON: "C:\\Python37-x64"
  PYTHON_VERSION: 3.7
  PYTHON_ARCH: 64

before_build:
  - cmd: mvn -v
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-storage-driver-nio:LATEST
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-storage-driver-coop:LATEST
  - cmd: mvn dependency:get -Dartifact=com.github.emc-mongoose:mongoose-base:LATEST

build: off
build_script:
  - cmd: cd %DRIVER_DIR%
# build driver fs
  - cmd: gradlew.bat clean jar

before_test:
  - ps: >
      $env:BASE_VERSION=$(ls -r $env:MAVEN_HOME
      |  where { $_ -match "mongoose-base-"} | Select-String -Pattern '\b\d\.\d\.\d\b' -AllMatches
      | % { $_.Matches } | % { $_.Value })

  - cmd: set EXT_DIR=C:\Users\appveyor\.mongoose\%BASE_VERSION%\ext\
  - cmd: mkdir %EXT_DIR%
  #  copy coop, nio drivers to .mongoose/ext
  - cmd: for /R %MAVEN_HOME% %%f in (mongoose-storage-driver-*.jar) do COPY %%f %EXT_DIR%
  #  copy fs driver to .mongoose/ext
  - cmd: for /R %DRIVER_DIR% %%f in (mongoose-storage-driver-*.jar) do COPY %%f %EXT_DIR%
  #  copy mongoose-base.jar to home dir
  - cmd: for /R %MAVEN_HOME% %%f in (mongoose-base-*.jar) do COPY %%f %HOME_DIR%

  - cmd: set PYTHONPATH=%DRIVER_DIR%\src\test\robot\lib;C:\Python37-x64\lib\site-packages
  - cmd: set PATH=%PATH%;C:\Python37-x64;C:\Python37-x64\Scripts
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - cmd: "%PYTHON%\\python.exe -m pip install -U virtualenv"
  - cmd: "%PYTHON%\\python.exe -m pip install -U requests"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework"
  - cmd: "%PYTHON%\\python.exe -m pip install -U robotframework-requests"
  - cmd: mkdir %PATH_TO_TEST_LOGS%

test_script:
  - cmd: robot --outputdir %PATH_TO_TEST_LOGS% --suite api.storage --include "fs" src\test\robot

on_failure:
  - cmd: appveyor PushArtifact %PATH_TO_TEST_LOGS%\log.html
